# myexceptions/exceptions.py

class IncidentNumberNotFoundException(Exception):
    pass
